services:
  postgres:
    ports: !override []

  redis:
    ports: !override []

  backend:
    ports: !override []

  frontend:
    build:
      context: ./frontend
      args:
        VITE_BASE_PATH: /transport/
        VITE_API_URL: /transport/api/v1
    ports: !override
      - "8081:80"
    volumes:
      - ./frontend/nginx.staging.conf:/etc/nginx/conf.d/default.conf
